website/static/js/gaEvents.js

New events tracked: Get Started click, click on Docs tab

RELATED: RAIL-1059 Add more GA events on the GoodData.UI homepage

---

docs/examples.md
docs/glossary.md
docs/ht_create_your_first_visualization.md
docs/installation.md
docs/sso.md
website/versioned_docs/version-5.0.0/examples.md
website/versioned_docs/version-5.0.0/glossary.md
website/versioned_docs/version-5.0.0/ht_create_your_first_visualization.md
website/versioned_docs/version-5.0.0/installation.md
website/versioned_docs/version-5.2.0/ht_create_your_first_visualization.md
website/versioned_docs/version-5.2.0/sso.md

RELATED: RAIL-1004 RAIL-1005 RAIL-1006 RAIL-1007 RAIL-1088 Feedback

---

docs/drillable_item.md
docs/on_fire_drill_event.md

This reverts commit 3a452631c5fae44bc2ea0ae41edd189ed4d29f6a and fixes some details in drilling documentation.

RELATED: BB-1332 Add AM drilling article again

---

docs/area_chart_component.md
docs/bar_chart_component.md
docs/chart_config.md
docs/column_chart_component.md

FEATURE: SD-287 Documentation for UI SDK API

---

docs/area_chart_component.md
docs/bar_chart_component.md
docs/bubble_chart_component.md
docs/column_chart_component.md
docs/donut_chart.md
docs/headline_component.md
docs/heatmap_component.md
docs/line_chart_component.md
docs/on_export_ready.md
docs/pie_chart.md
docs/pivot_table_component.md
docs/scatter_plot_component.md
docs/table_component.md
docs/treemap_component.md
docs/visualization_component.md
website/i18n/en.json
website/sidebars.json

PR for [SD-308](https://jira.intgdc.com/browse/SD-308)

FEATURE: SD-308 - Documentation in UI SDK for Export

---

docs/area_chart_component.md
docs/bar_chart_component.md
docs/column_chart_component.md

TRIVIAL: SD-287 add type and warning message

---

docs/afm.md
docs/filter_visual_components.md
docs/start_with_visual_components.md

Added documentation for text filters.

RELATED: ONE-3610 Text filter documentation

---

website/package.json
website/yarn.lock

Fixed high severity vulnerabilities from lodash but there are still present 3 moderate severity vulnerabilities which must be fixed in docusaurus. So we are not able to fix them.

FEATURE: FET-345 fixed dependency vulnerabilities

---

docs/on_export_ready.md

PR for [SD-206](https://jira.intgdc.com/browse/SD-206)

FEATURE: SD-206 - Support "Active filters context" in SDK

---

docs/10_vis__kpi_component.md
docs/10_vis__pivot_table_component.md

I made a couple of tweaks following https://github.com/gooddata/gooddata-ui/pull/320.

RELATED: Minor language edits after PR320

---

docs/01_intro__about_gooddataui.md
docs/02_start__connecting_backend.md
docs/30_tips__sso.md
docs/30_tips__use_angular_2.x.md
website/i18n/en.json
website/sidebars.json

* make Angular docs up-to-date (tested using a brand new Angular 10 app)
* update supported technologies section
* add docs about the available auth providers

RELATED: RAIL-1815 add missing docs

---

docs/30_tips__use_angular_2.x.md
docs/migration_guide_8.md
website/versioned_docs/version-8.0.0/30_tips__use_angular_2.x.md
website/versioned_docs/version-8.0.0/migration_guide_8.md

RAIL-2683 fix dead links in boilerplate migration
RAIL-2355 add missing package in angluar docs

RELATED: RAIL-2638, RAIL-2355 minor fixes

---

docs/01_intro__about_gooddataui.md
website/versioned_docs/version-8.0.0/01_intro__about_gooddataui.md

- Added informations about css variables polyfills

RELATED: RAIL-2731 Update info about mandatory IE11 polyfills

---

docs/02_start__no_boilerplate.md
website/versioned_docs/version-8.0.0/02_start__no_boilerplate.md

Fix the other place this was broken as well.

RELATED: RAIL-2764 add missing paren in code sample 2

---

website/i18n/en.json
website/versioned_docs/version-8.0.0/01_intro__about_gooddataui.md
website/versioned_docs/version-8.0.0/01_intro__interactive_examples.md
website/versioned_docs/version-8.0.0/01_intro__why_gdui.md
website/versioned_docs/version-8.0.0/02_start__no_boilerplate.md
website/versioned_docs/version-8.0.0/02_start__using_boilerplate.md
website/versioned_docs/version-8.0.0/10_vis__combo_chart_component.md
website/versioned_sidebars/version-8.0.0-sidebars.json

This makes the changes from the following PRs available in the 8.0.0 docs
* https://github.com/gooddata/gooddata-ui/pull/359
* https://github.com/gooddata/gooddata-ui/pull/360

RELATED: MKB-1716 retrofit launch docs to 8.0.0

---

docs/01_intro__why_gdui.md
docs/01_supported_versions.md
docs/10_vis__insight_view.md
docs/15_props__chart_config.md
docs/15_props__drillable_item.md
docs/15_props__on_drill.md
docs/15_props__on_export_ready.md
docs/15_props__on_legend_ready.md
docs/30_tips__embed_visualization.md
docs/30_tips__filter_visual_components.md
docs/30_tips__use_different_domains.md
website/i18n/en.json
website/versioned_docs/version-8.0.0/01_intro__why_gdui.md
website/versioned_docs/version-8.0.0/10_vis__insight_view.md
website/versioned_docs/version-8.0.0/15_props__chart_config.md
website/versioned_docs/version-8.0.0/15_props__drillable_item.md
website/versioned_docs/version-8.0.0/15_props__on_drill.md
website/versioned_docs/version-8.0.0/15_props__on_export_ready.md
website/versioned_docs/version-8.0.0/15_props__on_legend_ready.md
website/versioned_docs/version-8.0.0/30_tips__embed_visualization.md
website/versioned_docs/version-8.0.0/30_tips__filter_visual_components.md
website/versioned_docs/version-8.0.0/30_tips__use_different_domains.md

Also, made sure Supported Versions are available in the "next" section as well.

RELATED: RAIL-2784 fix InsightView docs and examples

---

docs/50_custom__component.md
website/versioned_docs/version-5.0.0/50_custom__component.md
website/versioned_docs/version-5.1.0/50_custom__component.md
website/versioned_docs/version-8.0.0/50_custom__component.md

Added only in versions 5.0.0 and newer, the 4.x version did not have this.

RELATED: RAIL-2332 add sdk prop to Execute component

---

docs/01_supported_versions.md
website/versioned_docs/version-5.0.0/01_supported_versions.md

The PR is to be merged on Feb 25, 2021, together with R222.

TRIVIAL: RAIL-2944 EOS date changed for GD.UI 7.x

---

docs/10_vis__date_filter_component.md

This reverts commit fdfee82050e0989266ca757c2fa3641f984c68bd.
We need to wait with that change after 8.2.0 drops

Revert "RELATED: RAIL-1843 remove date filter limitation"

---

docs/10_vis__date_filter_component.md

The names are now properly respected.

RELATED: RAIL-1843 remove date filter limitation

---

docs/02_start__no_boilerplate.md
website/versioned_docs/version-8.0.0/02_start__no_boilerplate.md
website/versioned_docs/version-8.1.0/02_start__no_boilerplate.md
website/versioned_docs/version-8.2.0/02_start__no_boilerplate.md

In the final code sample, some imports were missing causing confusion.

RELATED: RAIL-3152 fix code samples in no-bolierplate

---

docs/01_intro__about_gooddataui.md
docs/01_intro__framework_overview.md
docs/01_intro__interactive_examples.md
docs/01_intro__platform_intro.md
docs/01_intro__why_gdui.md
docs/01_supported_versions.md
docs/02_start__catalog_export.md
docs/02_start__connecting_backend.md
docs/02_start__execution_model.md
docs/02_start__no_boilerplate.md
docs/02_start__using_boilerplate.md
docs/06_cloudnative__integration.md
docs/06_cloudnative__introduction.md
docs/06_cloudnative__limitations.md
docs/06_cloudnative__local_dev.md
docs/20_misc__execution_model.md
docs/30_tips__backend_agnostic_apps.md
docs/30_tips__cors.md
docs/30_tips__sso.md
docs/50_custom__execution_new.md
website/TODO.md
website/i18n/en.json
website/sidebars.json
website/siteConfig.js
website/versioned_docs/version-5.0.0/01_supported_versions.md

Refactoring:
- Reworked side bar
- Reshuffled some content
- Moved parts of content into new files
Should be updated for tiger:
- Introduction
- Getting started 
JIRA: RAIL-3044

RELATED: RAIL-3044 - 8.3.0 docs

---

website/i18n/en.json
website/versioned_docs/version-8.3.0/15_props__date_filter_option.md

Previously this was removed only in the main page and was missed here.

RELATED: RAIL-2775 remove date filter limitation

---

website/pages/en/index.js

- Switched to lead to create new app = start with boilerplate
- 
JIRA: RAIL-3044

Update 'Get GoodData.UI' landing page

---

docs/10_vis__date_filter_component.md
docs/15_props__date_filter_option.md

- information about an issue with relativeForm dimension limits
JIRA: RAIL-1526

RelativeForm dimension limits issue

---

docs/10_vis__date_filter_component.md
docs/15_props__date_filter_option.md

- information about availableGranularities deprecation
- information about need of 'from' and 'to' parameters to be specified
JIRA: RAIL-1872

Update DateFilter documentation

---

website/versioned_docs/version-8.0.0/50_custom__create_new_visualization.md

Update docs according to the Execute component extension

---

docs/15_props__chart_config.md

- describe tooltip options to configure visibility
JIRA: RAIL-2929

Configure tooltip visibility

---

docs/10_vis__date_filter_component.md
docs/15_props__date_filter_option.md

- add removed status of availableGranularities in known issues
- remove availableGranularities from relativeForm options
JIRA: RAIL-1842

DateFilter relativeForm documentation

---

website/sidebars.json
website/versioned_sidebars/version-8.0.0-sidebars.json
website/versioned_sidebars/version-8.1.0-sidebars.json
website/versioned_sidebars/version-8.2.0-sidebars.json
website/versioned_sidebars/version-8.3.0-sidebars.json

RELATED: RAIL-2794 Remove items obsolete in SDK8 from sidebars

---

docs/50_custom__create_new_visualization.md
website/versioned_docs/version-8.0.0/50_custom__create_new_visualization.md

The changes were made in a wrong file which would make them effective
even for older versions of SDK8 that do not support the new props.
We need to move the changes to the correct file.
Original commit: a685038e5

TRIVIAL: move the changes made in a685038e5

---

docs/10_vis__insight_view.md
docs/15_props__chart_config.md

- add InsightTitle properties to docs
- fix chart config docs
JIRA: RAIL-3274

InsightView component documentation

---

website/pages/en/versions.js

Only the last of the previous major should be End of development
others need to be End of support.

RELATED: RAIL-3439 fix versions table

---

docs/30_tips__placeholders.md
website/i18n/en.json
website/sidebars.json

RELATED: RAIL-2800 Add placeholders documentation

---

docs/02_start__using_boilerplate.md

RELATED: RAIL-2092 - Remove obsolete statement in docs

---

docs/10_vis__kpi_component.md
website/versioned_docs/version-8.0.0/10_vis__kpi_component.md
website/versioned_docs/version-8.2.0/10_vis__kpi_component.md

- replace SDK 7 react-component import with SDK-8 sdk-ui one
JIRA: RAIL-3566

RELATED: RAIL-3566 invalid KPI import

---

docs/02_start__no_boilerplate.md
docs/06_cloudnative__integration.md
website/versioned_docs/version-8.3.0/02_start__no_boilerplate.md
website/versioned_docs/version-8.3.0/06_cloudnative__integration.md

Mention how to setup the app in a cross-domain use case.

RELATED: RAIL-3586 improve integration docs

---

docs/50_custom__result.md
website/versioned_docs/version-8.0.0/50_custom__result.md

RAIL-3644 Fix syntax mistakes in result docs

---

docs/10_vis__attribute_filter_button_component.md
docs/10_vis__attribute_filter_component.md
website/i18n/en.json

Related PR in SDK: https://github.com/gooddata/gooddata-ui-sdk/pull/1679
Also some remnant from the recent project -> workspace move
in auto-generated file was fixed (here project is correct, not workspace).

RELATED: RAIL-3622 changes to parentFilterOverAttribute

---

docs/10_vis__theme_provider.md

RAIL-3720 Update link to setting up backend and workspace

---

docs/18_dashboard_plugins.md
website/versioned_docs/version-8.7.0/18_dashboard_plugins.md

- Domain admin is not able to update the settings, this is only possible through the support ticket
JIRA: RAIL-3904

Correct dashboardPluginHosts setting info

---

docs/01_intro__why_gdui.md
website/i18n/en.json
website/versioned_docs/version-7.2.0/02_start__no_boilerplate.md
website/versioned_docs/version-7.8.0/30_tips__cors.md
website/versioned_docs/version-8.0.0/01_intro__interactive_examples.md
website/versioned_docs/version-8.0.0/01_intro__why_gdui.md
website/versioned_docs/version-8.0.0/02_start__connecting_backend.md
website/versioned_docs/version-8.0.0/02_start__no_boilerplate.md
website/versioned_docs/version-8.0.0/30_tips__cors.md
website/versioned_docs/version-8.1.0/01_intro__interactive_examples.md
website/versioned_docs/version-8.1.0/02_start__no_boilerplate.md
website/versioned_docs/version-8.2.0/02_start__no_boilerplate.md
website/versioned_docs/version-8.2.0/30_tips__cors.md
website/versioned_docs/version-8.3.0/01_intro__why_gdui.md
website/versioned_docs/version-8.3.0/02_start__no_boilerplate.md
website/versioned_docs/version-8.3.0/30_tips__cors.md
website/versioned_docs/version-8.6.0/02_start__no_boilerplate.md

- tutorial with usage of create-react-app@4 no longer works, mention it
- fix dead links
JIRA: RAIL-3904

Mention that CRA@4 no longer works

---

docs/15_props__chart_config.md
website/versioned_docs/version-8.0.0/15_props__chart_config.md
website/versioned_docs/version-8.2.0/15_props__chart_config.md
website/versioned_docs/version-8.4.0/15_props__chart_config.md
website/versioned_docs/version-8.7.0/15_props__chart_config.md

- Documentation on how to disable drilling from axis labels
JIRA: RAIL-3725

RELATED: RAIL-3725 Drill setup using catalog export docs

---

docs/01_intro__about_gooddataui.md
docs/10_vis__geo_pushpin_chart_component.md
docs/18_dashboard_plugins.md
docs/20_misc__time_over_time_comparison.md
docs/30_tips__cors.md
docs/30_tips__filter_visual_components.md
website/versioned_docs/version-7.2.0/02_start__no_boilerplate.md
website/versioned_docs/version-7.8.0/20_misc__time_over_time_comparison.md
website/versioned_docs/version-7.8.0/30_tips__cors.md
website/versioned_docs/version-7.8.0/30_tips__filter_visual_components.md
website/versioned_docs/version-8.0.0/02_start__no_boilerplate.md
website/versioned_docs/version-8.0.0/20_misc__time_over_time_comparison.md
website/versioned_docs/version-8.0.0/30_tips__cors.md
website/versioned_docs/version-8.0.0/30_tips__filter_visual_components.md
website/versioned_docs/version-8.1.0/02_start__no_boilerplate.md
website/versioned_docs/version-8.2.0/02_start__no_boilerplate.md
website/versioned_docs/version-8.2.0/20_misc__time_over_time_comparison.md
website/versioned_docs/version-8.2.0/30_tips__cors.md
website/versioned_docs/version-8.2.0/30_tips__filter_visual_components.md
website/versioned_docs/version-8.7.0/18_dashboard_plugins.md

Proofread the changes for the following PRs:
- https://github.com/gooddata/gooddata-ui/pull/472/files
- https://github.com/gooddata/gooddata-ui/pull/473/files
- https://github.com/gooddata/gooddata-ui/pull/474/files
- https://github.com/gooddata/gooddata-ui/pull/475/files

RELATED: Language edits related to previous PRs

---

docs/18_dashboard_plugins.md
website/versioned_docs/version-8.7.0/18_dashboard_plugins.md

…rsion of the Dashboard component

RELATED: RAIL-3910 Adding info about plugin validation

---

docs/breaking_changes_8.md
website/versioned_docs/version-8.0.0/breaking_changes_8.md
website/versioned_docs/version-8.8.0/breaking_changes_8.md

There were some placeholders forgotten from when the article was written.
JIRA: RAIL-3963

RELATED: RAIL-3963 Fix missing links in the Breaking changes page

---

docs/18_dashboard_component.md

RELATED: RAIL-3989 Docs on how to access dashboard state externally

---

docs/18_dashboard_component.md

- remove getInstance function as it is not available
- add getDashboardDispatchForDashboard and getDashboardSelectForDashboard
JIRA: RAIL-3989

RELATED: RAIL-3989 Update function list for access with latest

---

docs/30_tips__sso.md
website/i18n/en.json

* add SSO to sidebar for better searchability
* document the initiateSamlSso function
JIRA: RAIL-4020

RELATED: RAIL-4020 Improve SSO docs

---

docs/10_vis__attribute_filter_button_component.md

RELATED: RAIL-4003 Add note on AttributeFilterButton limitations

---

docs/10_vis__dashboard_view.md
website/versioned_docs/version-8.7.0/10_vis__dashboard_view.md

RELATED: RAIL-4046 Move the DashboardVIew removeal to 8.10

---

docs/18_dashboard_plugins_api.md

https://github.com/gooddata/gooddata-ui/pull/494/

RELATED: RAIL-3963 Proofread the changes from PR 494

---

website/siteConfig.js

RELATED: RAIL-3998 Migrate to the new DocSearch index

---

docs/02_start__choose_visualization_approach.md
docs/10_vis__start_with_visual_components.md
website/i18n/en.json
website/sidebars.json
website/versioned_docs/version-8.0.0/10_vis__start_with_visual_components.md
website/versioned_docs/version-8.2.0/10_vis__start_with_visual_components.md
website/versioned_docs/version-8.8.0/10_vis__start_with_visual_components.md

This should help newcomers decide which of the three ways
of visualizing data to use for their particular use case.
JIRA: RAIL-4055

RELATED: RAIL-4055 Add a visualization 'signpost' article

---

docs/18_dashboard_plugins_upgrade.md
website/i18n/en.json
website/sidebars.json
website/versioned_docs/version-8.7.0/18_dashboard_plugins_upgrade.md
website/versioned_sidebars/version-8.7.0-sidebars.json

RELATED: RAIL-4163 Add dashboard plugin upgrade guide

---

docs/18_dashboard_plugins_api.md

- Add documentation for asynchronous rendering utilities
- This is necessary to ensure that PDF exports of the Kpi Dashboards extended by Dashboard Plugin(s) with custom widgets will be rendered correctly
JIRA: RAIL-4179

Add documentation for dashboard plugins exports

---

docs/02_start__quickstart.md
docs/02_start_choose_dashboard_approach.md
docs/30_tips__use_different_domains.md
docs/support_options.md
website/i18n/en.json
website/sidebars.json

- to simplify orientation in the documentation for newcomers
- few minor fixes for other doc pages
JIRA: RAIL-4057

Add "Start with GoodData.UI" signpost

---

docs/02_start__choose_visualization_approach.md
docs/50_custom__create_new_visualization.md
docs/whats_new_8.md
website/i18n/en.json
website/sidebars.json

- mention all available aproaches how to get data for the custom visualizations (hooks, components, execution API)
- add links to live examples, so the developer can better understand how to use these components and hooks
- minor renamings
JIRA: RAIL-4057

Update docs about custom visualizations

---

website/siteConfig.js
website/static/js/scrollToSelected.js

RELATED: RAIL-4186 Add sidebar scroll support

---

website/i18n/en.json
website/pages/en/versions.js

It should be EoD as the rest of the SDK7 versions.
JIRA: RAIL-4087

RELATED: RAIL-4087 Fix 7.9.0 as EoS in the version picker

---

docs/18_dashboard_plugins_api.md

Time limit for rendering widget increased to 25mins

---

docs/01_intro__about_gooddataui.md
docs/01_intro__framework_overview.md
docs/01_intro__why_gdui.md
docs/01_supported_versions.md
docs/02_start__catalog_export.md
docs/02_start__execution_model.md
docs/02_start__quickstart.md
docs/02_start__using_boilerplate.md
docs/02_start_choose_dashboard_approach.md
docs/06_cloud__introduction.md
docs/06_cloudnative__authentication.md
docs/06_cloudnative__integration.md
docs/06_cloudnative__limitations.md
docs/06_cloudnative__local_dev.md
docs/10_vis__attribute_filter_button_component.md
docs/10_vis__date_filter_component.md
docs/10_vis__theme_provider.md
docs/15_props__data_sampling.md
docs/15_props__date_filter_option.md
docs/18_dashboard_intro.md
docs/18_dashboard_plugins.md
docs/18_dashboard_plugins_api.md
docs/20_misc__execution_model.md
docs/30_tips__backend_agnostic_apps.md
docs/breaking_changes_8.md
website/i18n/en.json
website/sidebars.json

Things done:
* mention GoodData Cloud along GoodData.CN and GoodData platform
* add Introduction to GoodData Cloud
* add supported versions entry for GoodData Cloud
* mention CORS settings in GoodData Cloud
* document Dashboard plugins not working in GoodData Cloud
JIRA: RAIL-4266

RELATED: RAIL-4266 Introduce GoodData Cloud

---

docs/02_start__no_boilerplate.md
docs/02_start__using_boilerplate.md

- Otherwise, GeoCharts are not working in boilerplate due to some babel transforms
- See related MapBox issue: mapbox/mapbox-gl-js#10565
- https://docs.mapbox.com/mapbox-gl-js/guides/install/#transpiling
- Also add step to create-react-app article
JIRA: RAIL-4312

Internet Explorer 11 is no longer supported in boilerplate

---

docs/18_dashboard_plugins_upgrade.md

- To avoid issues with missing css imports for local development
JIRA: RAIL-4207

Mention also harness files in plugin upgrade guide

---

docs/02_start__choose_visualization_approach.md

- Now, you can generate the visualization code directly inside Analytical Designer - mention it in visualizations signpost article
JIRA: RAIL-4296

RELATED: RAIL-4296 Mention tip about visualization code generation

---

docs/01_intro__about_gooddataui.md

Can't install CGRA with node version less than v16

---

docs/10_vis__insight_view.md
website/versioned_docs/version-8.0.0/10_vis__insight_view.md
website/versioned_docs/version-8.4.0/10_vis__insight_view.md

RELATED: RAIL-4394 Fix InsightView config prop type

---

docs/30_tips__placeholders.md
website/versioned_docs/version-8.4.0/30_tips__placeholders.md

It needs to be lowercase "c" to work properly. Also remove useless empty line.

TRIVIAL: fix anchor id

---

website/versioned_docs/version-8.10.0/18_dashboard_plugins.md

RAIL-4351: updates to version 8.10.0

---

docs/10_vis__insight_view.md
website/versioned_docs/version-8.4.0/10_vis__insight_view.md

RELATED: RAIL-4434 Mention the other CSS styles in InsightView

---

docs/06_cloudnative__limitations.md

RELATED: RAIL-4360 Document attribute elements being null

---

website/siteConfig.js

RELATED: RAIL-4350 Hide the deprecated AttributeElements options

---

docs/18_dashboard_component.md
docs/18_tips__improve_performance.md
docs/30_tips__improve_performance.md
website/i18n/en.json
website/sidebars.json

RELATED: RAIL-4439 Documentation on how to use withCaching decorator

---

docs/01_supported_versions.md
website/versioned_docs/version-8.10.0/01_supported_versions.md
website/versioned_docs/version-8.3.0/01_supported_versions.md
website/versioned_docs/version-8.4.0/01_supported_versions.md

Correct last available SDK minor version.

---

website/yarn.lock

There were problematic deps of `docusaurus`. Its deps were updated to satisfy caret versions.

RELATED: TNT-1075 Upgrade packages

---

docs/18_dashboard_plugins.md

RELATED: JIRA-4416 Doc for dashboard plugins

---

docs/18_dashboard_plugins_api.md

RELATED: RAIL - 4258 doc review

---

docs/10_vis__attribute_filter_component.md
docs/18_dashboard_plugins_api.md
docs/30_tips__create_custom_attribute_filter.md
docs/30_tips__filter_visual_components.md

- Add missing links to examples and api docs
JIRA: RAIL-4258

Update attribute filter examples links

---

docs/18_dashboard_plugins.md
website/versioned_docs/version-8.11.0/18_dashboard_plugins.md

RELATED: RAIL-4416 Remove plugin limitation, they are on Cloud, too

---

docs/01_intro__why_gdui.md
website/pages/en/index.js
website/versioned_docs/version-8.0.0/01_intro__why_gdui.md
website/versioned_docs/version-8.10.0/01_intro__why_gdui.md
website/versioned_docs/version-8.3.0/01_intro__why_gdui.md
website/versioned_docs/version-8.8.0/01_intro__why_gdui.md

- Force npx to install the latest stable version
JIRA: RAIL-4584

Correct CGRA command

---

docs/19_webcomponents_angular.md
docs/19_webcomponents_authentication.md
docs/19_webcomponents_intro.md
docs/19_webcomponents_vue.md
docs/30_tips__use_angular_2.x.md
website/i18n/en.json
website/sidebars.json
website/static/scss/highlighting.scss
website/versioned_docs/version-8.11.0/19_webcomponents_angular.md
website/versioned_docs/version-8.11.0/19_webcomponents_authentication.md
website/versioned_docs/version-8.11.0/19_webcomponents_vue.md
website/versioned_sidebars/version-8.11.0-sidebars.json

* A new article on Angular integration
* A new article on Vue integration
* Added numerous warnings about setup prerequisites, not supported plugins etc.

RELATED: RAIL-4669 Web components docs improvements

---

docs/10_vis__geo_pushpin_chart_component.md

New alternative how to define location props
JIRA: TNT-1151

RELATED: TNT-1151 Document new Geochart props

---

docs/18_dashboard_plugins_api.md

Mention that GoodData.UI charts require isExportMode in the configuration prop during export.
Add a note about handling exports and possible issues if you use interactivity in custom widgets.
JIRA: RAIL-4837

FEAT: RAIL-4837 Improve PDF export docs for dashboard plugins

---

website/versioned_docs/version-8.11.0/01_intro__about_gooddataui.md

Making sure the intro is up-to-date with our naming of the Dashboard component.

TRIVIAL: intro dashboardview -> dashboard

---

docs/10_vis__attribute_filter_button_component.md
docs/10_vis__attribute_filter_component.md

Attribute filter can be now as single selection
JIRA: TNT-1413

RELATED: TNT-1413 Document selection mode of filter
