gooddata/gooddata-ui

- docs/table_totals.md
The wording of the new sentence ("In addition, the subtotals are supported only for tables sorted by the first row attribute, and this is the default sorting for tables.") was approved by @evgeniabogranskaya
> RELATED: BB-1407 Document relation between sorting and subtotals.

- docs/filter_visual_components.md
Missed a couple of 'attribute filter supports URIs only'.. removed those. Added few more examples with text filters. Added re-iteration of text filter usage for simple measures (Filters set on a specific measure).
> RELATED: ONE-3610 Text filter documentation

- website/versioned_docs/version-6.3.0/ht_use_react_components_in_angular_2.x.md
Updated versions of dependencies and note mentioning the need to add a snippet to `polyfills.ts` file in order to run the application. Tested and updated back to v6.3.0 as we support two last major versions.
> BUGFIX: ONE-4190 fixed Angular 2+ documentation page

- docs/ht_create_your_first_visualization_toolkit.md
The ht_create_your_first_visualization_toolkit page was missing
in the "next" version. It is an exact copy of the 7.1.0 version.
> RELATED: RAIL-1701 add a page from 7.1.0 to next

- docs/model_helpers.md
- website/versioned_docs/version-7.1.0/model_helpers.md
Explain automatic vs. manual LocalIdentifiers in the Modelhelpers.
> BUGFIX: ONE-4227 LocalIdentifiers in Modelhelpers

- docs/model_helpers.md
- website/versioned_docs/version-6.2.0/model_helpers.md
- website/versioned_docs/version-7.1.0/model_helpers.md
Explain automatic vs. manual LocalIdentifiers in the Modelhelpers.
> BUGFIX: ONE-4227 LocalIdentifiers in Modelhelpers for SDK 6.2.0

- website/siteConfig.js
Originally, there was projectName property specified twice in the siteConfig.js. Once as "GoodData UI SDK" and then overridden to "gooddata-ui". I removed the second occurrence in commit 6f16b060ff90bdef4a1dd669ca6e8d01e5e513a2 and left there "GoodData UI SDK". Unfortunately, it broke documentation publishing as project name must not have space in it as I just found out. I restored the originally used value to fix the issue.
> TRIVIAL: Fix project name to allow site deploy

- website/siteConfig.js
Search showed links to multiple versions; which is an unwanted behaviour. We had to contact Algolia to modify the config file on their side and also to fix up sitemap issue on our side.
https://github.com/gooddata/gooddata-ui/pull/296
https://github.com/algolia/docsearch/issues/945
> BUGFIX: RAIL-2215 Fix header search behaviour

- website/pages/en/versions.js
For some reason, the content of 'next' is not accessible in 'docs'. The migration guide for v8 was linked to docs where the file was not found. Modified code so that it correctly adds the 'next'
JIRA: RAIL-2705
> RELATED: RAIL-2705 - Fix migration guide link

- docs/10_vis__area_chart_component.md
- docs/10_vis__insight_view.md
- docs/10_vis__pivot_table_component.md
The rows and columns were added to the first example to trick
the syntax higlighter to not highlight the example
(same as other visualizations).
Also, removed two obsolete sdk={<sdk>} examples.
> RELATED: RAIL-2707 fix Pivot examples

- docs/15_props__chart_config.md
- website/package.json
- website/versioned_docs/version-8.0.0/15_props__chart_config.md
- website/versioned_docs/version-8.2.0/15_props__chart_config.md
- website/yarn.lock
* fix link in Chart config so that it points to SDK8-relevant page
* bump dependencies to make `yarn audit` pass
> RELATED: RAIL-3069 fix chart config link, fix security warnings

- docs/10_vis__headline_component.md
- website/versioned_docs/version-5.0.0/10_vis__headline_component.md
- website/versioned_docs/version-5.2.0/10_vis__headline_component.md
- website/versioned_docs/version-6.3.0/10_vis__headline_component.md
- website/versioned_docs/version-8.0.0/10_vis__headline_component.md
Headline only supports measures. Fixed in all versions since it was
never accurate, Headline has always supported Measures only.
JIRA: RAIL-3306
> RELATED: RAIL-3306 Remove misleading sentence in Headline docs

- docs/10_vis__geo_pushpin_chart_component.md
- website/versioned_docs/version-8.0.0/10_vis__geo_pushpin_chart_component.md
Added to all SDK 8 versions, it seems the older versions
do not mention even onDrill there.
> RELATED: RAIL-3334 add drillableItems to Geo chart

- docs/01_intro__about_gooddataui.md
- docs/02_start__api_maturity.md
- website/versioned_docs/version-8.0.0/01_intro__about_gooddataui.md
- website/versioned_docs/version-8.2.0/01_intro__about_gooddataui.md
- website/versioned_docs/version-8.3.0/01_intro__about_gooddataui.md
* fix the version supported of TypeScript (it was always 4.0.2 for SDK8)
* document how we interpret semver in regards to types
> RELATED: RAIL-3395 document TypeScript semver

- website/sidebars.json
- website/versioned_sidebars/version-8.0.0-sidebars.json
- website/versioned_sidebars/version-8.1.0-sidebars.json
- website/versioned_sidebars/version-8.2.0-sidebars.json
- website/versioned_sidebars/version-8.3.0-sidebars.json
- website/versioned_sidebars/version-8.4.0-sidebars.json
The Table was removed in SDK8 so there is no reason to show it
in the left menu there.
> RELATED: RAIL-3486 remove Table mentions from SDK 8+

- docs/10_vis__pivot_table_component.md
JIRA: ONE-5060
Update documentation of autoresizing by new behavior of old option "viewport"
> Reuse "viewport" option of autoresizing again

- website/pages/en/versions.js
Adds links to API reference for versions that have it
(set to 8.5.0 and newer, the 8.4.0 is not production ready).
> RELATED: RAIL-3511 render API reference links

- docs/02_start__using_boilerplate.md
- website/versioned_docs/version-8.0.0/02_start__using_boilerplate.md
- website/versioned_docs/version-8.3.0/02_start__using_boilerplate.md
- website/versioned_docs/version-8.5.0/02_start__using_boilerplate.md
Previously, the most important link to use was drowned in a wall of text.
This adds headers so the user can scan the page more efficiently
if they don't care about the details described above.
> RELATED: RAIL-3587 make the How to use more prominent

- docs/30_tips__use_different_domains.md
- docs/breaking_changes_8.md
- website/versioned_docs/version-4.1.1/30_tips__use_with_vanilla_js.md
- website/versioned_docs/version-5.0.0/30_tips__use_different_domains.md
- website/versioned_docs/version-8.0.0/30_tips__use_different_domains.md
- website/versioned_docs/version-8.0.0/breaking_changes_8.md
Handle pattern "<projectId" → "<workspaceId" and some missing cases
> RELATED: SD-1688 Rename project to workspace in GD.UI SDK docs

- website/versioned_docs/version-6.0.0/02_start__no_boilerplate.md
- website/versioned_docs/version-6.1.0/02_start__no_boilerplate.md
- website/versioned_docs/version-6.3.0/02_start__no_boilerplate.md
- website/versioned_docs/version-7.1.0/02_start__no_boilerplate.md
- website/versioned_docs/version-7.2.0/02_start__no_boilerplate.md
- website/versioned_docs/version-8.0.0/02_start__no_boilerplate.md
- website/versioned_docs/version-8.1.0/02_start__no_boilerplate.md
- website/versioned_docs/version-8.2.0/02_start__no_boilerplate.md
This prevents errors with version 5 of the create-react-app
that is not working with neither SDK7 nor SDK8 at the moment.
Also remove nonsensical mention of @gooddata/typings in versions related
to SDK8, typings are only relevant to versions <= 7.
JIRA: RAIL-3921
> RELATED: RAIL-3921 Pin create-react-app calls to version 4

- docs/01_intro__about_gooddataui.md
- UI.SDK >= 8.8 no longer support Geo Pushpin Chart in Internet Explorer 11
JIRA: RAIL-3923
> Mention the loss of support for Geo Pushpin Chart in IE11

- docs/01_intro__about_gooddataui.md
- website/i18n/en.json
The change in en.json was automatic, caused by it being previously sorted by Czech ordering (ch as a letter).
JIRA: RAIL-3906
> RELATED: RAIL-3906 Mention React 17 compatibility

- docs/18_dashboard_plugins.md
We now share the sdk-ui-dashboard as well and no longer share react-intl.
JIRA: RAIL-3951
> RELATED: RAIL-3951 Reflect changes to plugin building

- docs/breaking_changes_8.md
- website/i18n/en.json
- website/versioned_docs/version-8.0.0/breaking_changes_8.md
- website/versioned_docs/version-8.3.0/breaking_changes_8.md
The previous fix in this area was not ideal, since the GoodData.CN parts
are only available since 8.3.0, so the older versions had dead links.
Hence a new version of the page was added to cover versions 8.3.0 and up.
JIRA: RAIL-3963
> RELATED: RAIL-3963 Fix breaking changes links in version 8.0.0

- docs/01_intro__roadmap.md
- website/siteConfig.js
- website/static/js/resizeRoadmap.js
- website/versioned_docs/version-8.7.0/01_intro__roadmap.md
Since there is no way to fit the iframe to fit its contents as it is cross-origin, we instead try to fill as much of the viewport as possible on the iframe load.
> RELATED: RAIL-4021 Automatically resize Roadmap

- docs/01_intro__roadmap.md
- website/static/js/resizeRoadmap.js
- website/versioned_docs/version-8.7.0/01_intro__roadmap.md
This is to prevent extremely small heights that make Productboard barely usable.
Also unify the min height and the default height.
JIRA: RAIL-4021
> RELATED: RAIL-4021 Add min height to roadmap

- docs/18_dashboard_plugins_api.md
- example was wrong, decoration must happen in the provider, not in the component render function (otherwise it can lead to infinite re-render loop)
- mention it explicitly in the comment to avoid future confusion
JIRA: RAIL-4227
> Correct example of the plugin decorator

- docs/10_vis__dashboard_view.md
- docs/10_vis__theme_provider.md
- docs/50_custom__create_new_visualization.md
- website/i18n/en.json
- website/siteConfig.js
- website/versioned_docs/version-8.1.0/10_vis__theme_provider.md
- website/versioned_docs/version-8.2.0/10_vis__theme_provider.md
- website/versioned_docs/version-8.3.0/10_vis__theme_provider.md
- website/versioned_docs/version-8.6.0/10_vis__theme_provider.md
This will avoid some confusion with people finding old irrelevant pages
using the Algolia search.
Also hide DashboardView in a way that will not break older versions and
fix some dead links.
JIRA: RAIL-4337
> RELATED: RAIL-4337 Hide irrelevant old pages in newer versions

- docs/50_custom__component.md
- website/siteConfig.js
- website/versioned_docs/version-5.1.0/50_custom__component.md
- website/versioned_docs/version-8.0.0/50_custom__component.md
In SDK8 the page should no longer be shown as it was replaced by
a whole section about custom components.
JIRA: RAIL-3410
> RELATED: RAIL-3410 Remove bad practice from Execute, hide it in SDK8

- docs/19_webcomponents_insight.md
- website/i18n/en.json
- website/versioned_docs/version-8.11.0/19_webcomponents_insight.md
Two links got mixed up.
Hey, @no23reason. When I build the project to test the fix, there is also a `website/i18n/en.json` file updated. Should I commit it as well? Thanks!
> RELATED: RAIL-4665 Fixed invalid links in WebComponents docs
